### ISSUE TITLE
popplerqt4.version() and popplerqt4.poppler_version() are not available on Mac OS X

### ISSUE THREAD

**Issue by dliessi** [wbsoft/python-poppler-qt4#9]
```
Python 2.7.9 (default, Dec 15 2014, 12:01:32) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import popplerqt4
>>> popplerqt4.version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'version'
>>> popplerqt4.poppler_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'poppler_version'
>>> 
```

**Comment by dliessi** [comment]
Please ignore this: I was still using 0.18.2; with version 0.24.0 everything works as expected.
Sorry for the noise.
